/*
 ===============================================================================
 Project      : FlowStack SaaS Analytics
 File         : 05_advanced_sql.sql
 
 Description  :
 Demonstrates advanced SQL techniques to solve real-world SaaS
 business problems using Common Table Expressions (CTEs),
 Window Functions, Ranking Functions, Analytical Functions,
 and Conditional Logic.
 
 Topics Covered :
 • Common Table Expressions (CTEs)
 • Window Functions
 • Ranking Functions
 • Running Totals
 • LAG & LEAD
 • CASE Expressions
 ===============================================================================
 */
USE flowstack_analytics;
-- -----------------------------------------------------------------------------
-- Q1. Top Revenue Generating Customers
-- Objective : Rank customers based on total revenue generated.
-- -----------------------------------------------------------------------------
WITH customer_revenue AS (
    SELECT c.customer_id,
        c.company_name,
        ROUND(SUM(i.amount), 2) AS total_revenue
    FROM customers c
        JOIN subscriptions s ON c.customer_id = s.customer_id
        JOIN invoices i ON s.subscription_id = i.subscription_id
    WHERE i.payment_status = 'Paid'
    GROUP BY c.customer_id,
        c.company_name
)
SELECT *
FROM customer_revenue
ORDER BY total_revenue DESC;
-- -----------------------------------------------------------------------------
-- Q2. Customers Above Average Revenue
-- Objective : Identify customers whose revenue exceeds the average.
-- -----------------------------------------------------------------------------
WITH customer_revenue AS (
    SELECT c.customer_id,
        c.company_name,
        SUM(i.amount) AS total_revenue
    FROM customers c
        JOIN subscriptions s ON c.customer_id = s.customer_id
        JOIN invoices i ON s.subscription_id = i.subscription_id
    WHERE i.payment_status = 'Paid'
    GROUP BY c.customer_id,
        c.company_name
)
SELECT *
FROM customer_revenue
WHERE total_revenue > (
        SELECT AVG(total_revenue)
        FROM customer_revenue
    )
ORDER BY total_revenue DESC;
-- -----------------------------------------------------------------------------
-- Q3. Revenue by Subscription Plan
-- Objective : Calculate total revenue generated by each subscription plan.
-- -----------------------------------------------------------------------------
WITH plan_revenue AS (
    SELECT p.plan_name,
        SUM(i.amount) AS total_revenue
    FROM plans p
        JOIN subscriptions s ON p.plan_id = s.plan_id
        JOIN invoices i ON s.subscription_id = i.subscription_id
    WHERE i.payment_status = 'Paid'
    GROUP BY p.plan_name
)
SELECT *
FROM plan_revenue
ORDER BY total_revenue DESC;
-- =============================================================================
-- SECTION 2 : RANKING FUNCTIONS
-- Purpose:
-- Rank customers, subscription plans, and account managers
-- based on business performance.
-- =============================================================================
-- -----------------------------------------------------------------------------
-- Q4. Rank Customers by Revenue
-- Objective : Assign a unique rank to each customer based on revenue generated.
-- -----------------------------------------------------------------------------
WITH customer_revenue AS (
    SELECT c.customer_id,
        c.company_name,
        ROUND(SUM(i.amount), 2) AS total_revenue
    FROM customers c
        JOIN subscriptions s ON c.customer_id = s.customer_id
        JOIN invoices i ON s.subscription_id = i.subscription_id
    WHERE i.payment_status = 'Paid'
    GROUP BY c.customer_id,
        c.company_name
)
SELECT customer_id,
    company_name,
    total_revenue,
    ROW_NUMBER() OVER (
        ORDER BY total_revenue DESC
    ) AS revenue_rank
FROM customer_revenue;
-- -----------------------------------------------------------------------------
-- Q5. Rank Subscription Plans by Revenue
-- Objective : Rank subscription plans based on total revenue generated.
-- -----------------------------------------------------------------------------
WITH plan_revenue AS (
    SELECT p.plan_name,
        ROUND(SUM(i.amount), 2) AS total_revenue
    FROM plans p
        JOIN subscriptions s ON p.plan_id = s.plan_id
        JOIN invoices i ON s.subscription_id = i.subscription_id
    WHERE i.payment_status = 'Paid'
    GROUP BY p.plan_name
)
SELECT plan_name,
    total_revenue,
    RANK() OVER (
        ORDER BY total_revenue DESC
    ) AS revenue_rank
FROM plan_revenue;
-- -----------------------------------------------------------------------------
-- Q6. Dense Rank Account Managers by Revenue
-- Objective : Rank account managers while avoiding gaps in ranking.
-- -----------------------------------------------------------------------------
WITH manager_revenue AS (
    SELECT am.manager_name,
        ROUND(SUM(i.amount), 2) AS total_revenue
    FROM account_managers am
        JOIN customers c ON am.manager_id = c.manager_id
        JOIN subscriptions s ON c.customer_id = s.customer_id
        JOIN invoices i ON s.subscription_id = i.subscription_id
    WHERE i.payment_status = 'Paid'
    GROUP BY am.manager_name
)
SELECT manager_name,
    total_revenue,
    DENSE_RANK() OVER (
        ORDER BY total_revenue DESC
    ) AS manager_rank
FROM manager_revenue;
-- =============================================================================
-- End of Ranking Functions
-- =============================================================================
-- =============================================================================
-- SECTION 3 : WINDOW AGGREGATE FUNCTIONS
-- Purpose:
-- Perform advanced analytical calculations using window aggregate
-- functions while preserving individual row-level details.
-- =============================================================================
-- -----------------------------------------------------------------------------
-- Q7. Revenue Contribution of Each Invoice
-- Objective : Calculate each invoice amount along with the overall
-- revenue and its percentage contribution.
-- -----------------------------------------------------------------------------
SELECT invoice_id,
    amount,
    SUM(amount) OVER () AS total_revenue,
    ROUND(
        (amount / SUM(amount) OVER ()) * 100,
        2
    ) AS revenue_percentage
FROM invoices
WHERE payment_status = 'Paid';
-- -----------------------------------------------------------------------------
-- Q8. Average Invoice Amount by Payment Method
-- Objective : Compare each invoice against the average invoice amount
-- within its payment method.
-- -----------------------------------------------------------------------------
SELECT invoice_id,
    payment_method,
    amount,
    ROUND(
        AVG(amount) OVER (
            PARTITION BY payment_method
        ),
        2
    ) AS average_payment_method_amount
FROM invoices
WHERE payment_status = 'Paid';
-- -----------------------------------------------------------------------------
-- Q9. Customer Revenue Compared to Regional Revenue
-- Objective : Compare customer revenue with the total revenue generated
-- within the customer's region.
-- -----------------------------------------------------------------------------
WITH customer_revenue AS (
    SELECT c.customer_id,
        c.company_name,
        c.region,
        SUM(i.amount) AS total_revenue
    FROM customers c
        JOIN subscriptions s ON c.customer_id = s.customer_id
        JOIN invoices i ON s.subscription_id = i.subscription_id
    WHERE i.payment_status = 'Paid'
    GROUP BY c.customer_id,
        c.company_name,
        c.region
)
SELECT customer_id,
    company_name,
    region,
    total_revenue,
    SUM(total_revenue) OVER (PARTITION BY region) AS regional_revenue
FROM customer_revenue;
-- =============================================================================
-- End of Window Aggregate Functions
-- =============================================================================
-- =============================================================================
-- SECTION 4 : RUNNING TOTALS & MOVING AVERAGES
-- Purpose:
-- Analyze cumulative business performance and identify
-- revenue trends over time using window functions.
-- =============================================================================
-- -----------------------------------------------------------------------------
-- Q10. Running Total of Monthly Revenue
-- Objective : Calculate cumulative revenue earned over time.
-- -----------------------------------------------------------------------------
WITH monthly_revenue AS (
    SELECT DATE_FORMAT(invoice_date, '%Y-%m') AS revenue_month,
        SUM(amount) AS monthly_revenue
    FROM invoices
    WHERE payment_status = 'Paid'
    GROUP BY DATE_FORMAT(invoice_date, '%Y-%m')
)
SELECT revenue_month,
    monthly_revenue,
    SUM(monthly_revenue) OVER (
        ORDER BY revenue_month
    ) AS running_total_revenue
FROM monthly_revenue;
-- -----------------------------------------------------------------------------
-- Q11. Running Total of Customer Signups
-- Objective : Track cumulative customer growth over time.
-- -----------------------------------------------------------------------------
WITH monthly_signups AS (
    SELECT DATE_FORMAT(signup_date, '%Y-%m') AS signup_month,
        COUNT(*) AS new_customers
    FROM customers
    GROUP BY DATE_FORMAT(signup_date, '%Y-%m')
)
SELECT signup_month,
    new_customers,
    SUM(new_customers) OVER (
        ORDER BY signup_month
    ) AS cumulative_customers
FROM monthly_signups;
-- -----------------------------------------------------------------------------
-- Q12. Three-Month Moving Average of Revenue
-- Objective : Smooth monthly revenue fluctuations by calculating
-- a rolling three-month average.
-- -----------------------------------------------------------------------------
WITH monthly_revenue AS (
    SELECT DATE_FORMAT(invoice_date, '%Y-%m') AS revenue_month,
        SUM(amount) AS monthly_revenue
    FROM invoices
    WHERE payment_status = 'Paid'
    GROUP BY DATE_FORMAT(invoice_date, '%Y-%m')
)
SELECT revenue_month,
    monthly_revenue,
    ROUND(
        AVG(monthly_revenue) OVER (
            ORDER BY revenue_month ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
        ),
        2
    ) AS moving_average_revenue
FROM monthly_revenue;
-- =============================================================================
-- End of Running Totals & Moving Averages
-- =============================================================================
-- =============================================================================
-- SECTION 5 : LAG() & LEAD() FUNCTIONS
-- Purpose:
-- Compare current performance with previous and future periods
-- using analytical window functions.
-- =============================================================================
-- -----------------------------------------------------------------------------
-- Q13. Month-over-Month Revenue Growth
-- Objective : Compare each month's revenue with the previous month.
-- -----------------------------------------------------------------------------
WITH monthly_revenue AS (
    SELECT DATE_FORMAT(invoice_date, '%Y-%m') AS revenue_month,
        SUM(amount) AS monthly_revenue
    FROM invoices
    WHERE payment_status = 'Paid'
    GROUP BY DATE_FORMAT(invoice_date, '%Y-%m')
)
SELECT revenue_month,
    monthly_revenue,
    LAG(monthly_revenue) OVER (
        ORDER BY revenue_month
    ) AS previous_month_revenue,
    ROUND(
        monthly_revenue - LAG(monthly_revenue) OVER (
            ORDER BY revenue_month
        ),
        2
    ) AS revenue_difference
FROM monthly_revenue;
-- -----------------------------------------------------------------------------
-- Q14. Month-over-Month Revenue Growth Percentage
-- Objective : Calculate percentage growth compared to the previous month.
-- -----------------------------------------------------------------------------
WITH monthly_revenue AS (
    SELECT DATE_FORMAT(invoice_date, '%Y-%m') AS revenue_month,
        SUM(amount) AS monthly_revenue
    FROM invoices
    WHERE payment_status = 'Paid'
    GROUP BY DATE_FORMAT(invoice_date, '%Y-%m')
)
SELECT revenue_month,
    monthly_revenue,
    ROUND(
        (
            (
                monthly_revenue - LAG(monthly_revenue) OVER (
                    ORDER BY revenue_month
                )
            ) / LAG(monthly_revenue) OVER (
                ORDER BY revenue_month
            )
        ) * 100,
        2
    ) AS revenue_growth_percentage
FROM monthly_revenue;
-- -----------------------------------------------------------------------------
-- Q15. Compare Current and Next Month Revenue
-- Objective : Display current month's revenue along with the
-- following month's revenue for forecasting and planning.
-- -----------------------------------------------------------------------------
WITH monthly_revenue AS (
    SELECT DATE_FORMAT(invoice_date, '%Y-%m') AS revenue_month,
        SUM(amount) AS monthly_revenue
    FROM invoices
    WHERE payment_status = 'Paid'
    GROUP BY DATE_FORMAT(invoice_date, '%Y-%m')
)
SELECT revenue_month,
    monthly_revenue,
    LEAD(monthly_revenue) OVER (
        ORDER BY revenue_month
    ) AS next_month_revenue
FROM monthly_revenue;
-- =============================================================================
-- End of LAG() & LEAD() Functions
-- =============================================================================