/*
 ===============================================================================
 Project      : FlowStack SaaS Analytics
 File         : 05_advanced_sql.sql
 
 Description  :
 Demonstrates advanced SQL techniques to solve real-world SaaS
 business problems using Common Table Expressions (CTEs),
 Window Functions, Ranking Functions, Analytical Functions,
 and Conditional Logic.
 
 Topics Covered :
 • Common Table Expressions (CTEs)
 • Window Functions
 • Ranking Functions
 • Running Totals
 • LAG & LEAD
 • CASE Expressions
 ===============================================================================
 */
USE flowstack_analytics;
-- -----------------------------------------------------------------------------
-- Q1. Top Revenue Generating Customers
-- Objective : Rank customers based on total revenue generated.
-- -----------------------------------------------------------------------------
WITH customer_revenue AS (
    SELECT c.customer_id,
        c.company_name,
        ROUND(SUM(i.amount), 2) AS total_revenue
    FROM customers c
        JOIN subscriptions s ON c.customer_id = s.customer_id
        JOIN invoices i ON s.subscription_id = i.subscription_id
    WHERE i.payment_status = 'Paid'
    GROUP BY c.customer_id,
        c.company_name
)
SELECT *
FROM customer_revenue
ORDER BY total_revenue DESC;
-- -----------------------------------------------------------------------------
-- Q2. Customers Above Average Revenue
-- Objective : Identify customers whose revenue exceeds the average.
-- -----------------------------------------------------------------------------
WITH customer_revenue AS (
    SELECT c.customer_id,
        c.company_name,
        SUM(i.amount) AS total_revenue
    FROM customers c
        JOIN subscriptions s ON c.customer_id = s.customer_id
        JOIN invoices i ON s.subscription_id = i.subscription_id
    WHERE i.payment_status = 'Paid'
    GROUP BY c.customer_id,
        c.company_name
)
SELECT *
FROM customer_revenue
WHERE total_revenue > (
        SELECT AVG(total_revenue)
        FROM customer_revenue
    )
ORDER BY total_revenue DESC;
-- -----------------------------------------------------------------------------
-- Q3. Revenue by Subscription Plan
-- Objective : Calculate total revenue generated by each subscription plan.
-- -----------------------------------------------------------------------------
WITH plan_revenue AS (
    SELECT p.plan_name,
        SUM(i.amount) AS total_revenue
    FROM plans p
        JOIN subscriptions s ON p.plan_id = s.plan_id
        JOIN invoices i ON s.subscription_id = i.subscription_id
    WHERE i.payment_status = 'Paid'
    GROUP BY p.plan_name
)
SELECT *
FROM plan_revenue
ORDER BY total_revenue DESC;