/*
 ===============================================================================
 Project      : FlowStack SaaS Analytics
 File         : 06_views.sql
 
 Description  :
 Creates reusable SQL views for reporting, dashboard development,
 and business intelligence. These views simplify complex joins and
 provide ready-to-use datasets for analysis and visualization.
 ===============================================================================
 */
USE flowstack_analytics;
-- =============================================================================
-- VIEW 1 : CUSTOMER SUBSCRIPTION OVERVIEW
-- Purpose:
-- Displays customer information along with subscription details.
-- =============================================================================
CREATE VIEW vw_customer_subscription_overview AS
SELECT c.customer_id,
    c.company_name,
    c.industry,
    c.region,
    p.plan_name,
    s.billing_cycle,
    s.subscription_status,
    s.subscription_start,
    s.subscription_end
FROM customers c
    JOIN subscriptions s ON c.customer_id = s.customer_id
    JOIN plans p ON s.plan_id = p.plan_id;
-- =============================================================================
-- VIEW 2 : REVENUE SUMMARY
-- Purpose:
-- Displays invoice and payment information for revenue reporting.
-- =============================================================================
CREATE VIEW vw_revenue_summary AS
SELECT c.customer_id,
    c.company_name,
    p.plan_name,
    i.invoice_id,
    i.invoice_date,
    i.amount,
    i.payment_method,
    i.payment_status
FROM customers c
    JOIN subscriptions s ON c.customer_id = s.customer_id
    JOIN plans p ON s.plan_id = p.plan_id
    JOIN invoices i ON s.subscription_id = i.subscription_id;
-- =============================================================================
-- VIEW 3 : CUSTOMER LIFETIME REVENUE
-- Purpose:
-- Displays total revenue generated by each customer.
-- =============================================================================
CREATE VIEW vw_customer_lifetime_revenue AS
SELECT c.customer_id,
    c.company_name,
    ROUND(SUM(i.amount), 2) AS lifetime_revenue
FROM customers c
    JOIN subscriptions s ON c.customer_id = s.customer_id
    JOIN invoices i ON s.subscription_id = i.subscription_id
WHERE i.payment_status = 'Paid'
GROUP BY c.customer_id,
    c.company_name;
-- =============================================================================
-- VIEW 4 : SUPPORT PERFORMANCE
-- Purpose:
-- Displays customer support ticket details for reporting.
-- =============================================================================
CREATE VIEW vw_support_performance AS
SELECT c.customer_id,
    c.company_name,
    st.ticket_id,
    st.category,
    st.priority,
    st.status,
    st.resolution_hours,
    st.customer_rating
FROM customers c
    JOIN support_tickets st ON c.customer_id = st.customer_id;
-- =============================================================================
-- VIEW 5 : PRODUCT USAGE SUMMARY
-- Purpose:
-- Displays customer product usage metrics.
-- =============================================================================
CREATE VIEW vw_product_usage_summary AS
SELECT c.customer_id,
    c.company_name,
    u.usage_month,
    u.active_users,
    u.api_requests,
    u.storage_used_gb,
    u.login_count
FROM customers c
    JOIN usage_logs u ON c.customer_id = u.customer_id;
-- =============================================================================
-- VIEW 6 : ACCOUNT MANAGER PERFORMANCE
-- Purpose:
-- Displays customer assignments and monthly targets for account managers.
-- =============================================================================
CREATE VIEW vw_account_manager_performance AS
SELECT am.manager_id,
    am.manager_name,
    c.customer_id,
    c.company_name,
    mt.target_month,
    mt.target_revenue,
    mt.achieved_revenue
FROM account_managers am
    LEFT JOIN customers c ON am.manager_id = c.manager_id
    LEFT JOIN monthly_targets mt ON am.manager_id = mt.manager_id;
-- =============================================================================
-- Verify Created Views
-- =============================================================================
SHOW FULL TABLES
WHERE Table_type = 'VIEW';
-- =============================================================================
-- VIEWS CREATED SUCCESSFULLY
--
-- Views Created:
-- • vw_customer_subscription_overview
-- • vw_revenue_summary
-- • vw_customer_lifetime_revenue
-- • vw_support_performance
-- • vw_product_usage_summary
-- • vw_account_manager_performance
-- =============================================================================