/*
 ===============================================================================
 Project      : FlowStack SaaS Analytics
 File         : 08_stored_procedures.sql
 
 Description  :
 Creates reusable stored procedures for common business operations
 and reporting. These procedures simplify report generation and
 improve code reusability.
 ===============================================================================
 */
USE flowstack_analytics;
-- -----------------------------------------------------------------------------
-- Procedure : sp_customer_revenue
-- Purpose   : Returns total revenue generated by a specific customer.
-- -----------------------------------------------------------------------------
DELIMITER $$ CREATE PROCEDURE sp_customer_revenue (IN p_customer_id INT) BEGIN
SELECT c.customer_id,
    c.company_name,
    ROUND(SUM(i.amount), 2) AS total_revenue
FROM customers c
    JOIN subscriptions s ON c.customer_id = s.customer_id
    JOIN invoices i ON s.subscription_id = i.subscription_id
WHERE c.customer_id = p_customer_id
    AND i.payment_status = 'Paid'
GROUP BY c.customer_id,
    c.company_name;
END $$ DELIMITER;
-- -----------------------------------------------------------------------------
-- Procedure : sp_revenue_by_region
-- Purpose   : Returns revenue generated for a selected region.
-- -----------------------------------------------------------------------------
DELIMITER $$ CREATE PROCEDURE sp_revenue_by_region (IN p_region VARCHAR(50)) BEGIN
SELECT c.region,
    ROUND(SUM(i.amount), 2) AS total_revenue
FROM customers c
    JOIN subscriptions s ON c.customer_id = s.customer_id
    JOIN invoices i ON s.subscription_id = i.subscription_id
WHERE c.region = p_region
    AND i.payment_status = 'Paid'
GROUP BY c.region;
END $$ DELIMITER;
-- -----------------------------------------------------------------------------
-- Procedure : sp_manager_performance
-- Purpose   : Returns customer count and revenue managed by an account manager.
-- -----------------------------------------------------------------------------
DELIMITER $$ CREATE PROCEDURE sp_manager_performance (IN p_manager_id INT) BEGIN
SELECT am.manager_name,
    COUNT(DISTINCT c.customer_id) AS total_customers,
    ROUND(SUM(i.amount), 2) AS total_revenue
FROM account_managers am
    JOIN customers c ON am.manager_id = c.manager_id
    JOIN subscriptions s ON c.customer_id = s.customer_id
    JOIN invoices i ON s.subscription_id = i.subscription_id
WHERE am.manager_id = p_manager_id
    AND i.payment_status = 'Paid'
GROUP BY am.manager_name;
END $$ DELIMITER;
-- -----------------------------------------------------------------------------
-- Procedure : sp_monthly_revenue
-- Purpose   : Returns monthly revenue for a specified year.
-- -----------------------------------------------------------------------------
DELIMITER $$ CREATE PROCEDURE sp_monthly_revenue (IN p_year INT) BEGIN
SELECT MONTH(invoice_date) AS month_number,
    MONTHNAME(invoice_date) AS month_name,
    ROUND(SUM(amount), 2) AS monthly_revenue
FROM invoices
WHERE YEAR(invoice_date) = p_year
    AND payment_status = 'Paid'
GROUP BY MONTH(invoice_date),
    MONTHNAME(invoice_date)
ORDER BY MONTH(invoice_date);
END $$ DELIMITER;
-- -----------------------------------------------------------------------------
-- Procedure : sp_customer_support_summary
-- Purpose   : Returns all support tickets for a specific customer.
-- -----------------------------------------------------------------------------
DELIMITER $$ CREATE PROCEDURE sp_customer_support_summary (IN p_customer_id INT) BEGIN
SELECT c.company_name,
    st.ticket_id,
    st.category,
    st.priority,
    st.status,
    st.resolution_hours,
    st.customer_rating
FROM customers c
    JOIN support_tickets st ON c.customer_id = st.customer_id
WHERE c.customer_id = p_customer_id;
END $$ DELIMITER;
-- =============================================================================
-- Verify Stored Procedures
-- =============================================================================
SHOW PROCEDURE STATUS
WHERE Db = 'flowstack_analytics';
-- =============================================================================
-- STORED PROCEDURES CREATED SUCCESSFULLY
--
-- Procedures Created:
-- • sp_customer_revenue
-- • sp_revenue_by_region
-- • sp_manager_performance
-- • sp_monthly_revenue
-- • sp_customer_support_summary
-- =============================================================================